# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Generic sphinx-needs filter functions for ``needpie`` directives.

These functions are fully parameterizable and designed to be called directly
by consumers of docs-as-code (e.g. reference-integration repos) when they
pull in the ``score_docs_as_code`` Bazel module.  All functions follow the
sphinx-needs ``filter-func`` signature convention:

.. code-block:: python

    def func(needs: list[NeedItem], results: list[int], **kwargs) -> None: ...

Arguments are injected from the ``:filter-func:`` call-site as positional
``arg1``, ``arg2``, … keyword arguments.

Example usage in RST::

    .. needpie:: My Requirements Coverage
       :labels: Linked, Not Linked
       :filter-func: score_metrics.sphinx_filters.generic_pie_linked_items(std_req__mystandard__, gd_)

"""

from __future__ import annotations

from typing import Any

from score_metrics.traceability_metrics import CALCULATED_METRICS
from sphinx_needs.need_item import NeedItem


def _matches_source_selector(need: NeedItem, selector: str) -> bool:
    """Return whether a need matches a source selector.

    The selector is treated as a prefix and matched against both ``type`` and
    ``id`` so filters remain robust when metamodels use explicit id prefixes
    that are not coupled to directive names.
    """
    need_type = str(need.get("type", ""))
    need_id = str(need.get("id", ""))
    return need_type.startswith(selector) or need_id.startswith(selector)


def generic_pie_linked_items(
    needs: list[NeedItem], results: list[int], **kwargs: Any
) -> None:
    """Count target IDs by whether they are linked by selected source needs.

    Arguments are passed via ``arg1`` (target ID prefix), ``arg2`` (source
    selector prefix, matched against source ``type`` and ``id``), and ``arg3``
    (link field name, default ``complies``).
    """
    results.clear()
    id_prefix = str(kwargs.get("arg1", ""))
    source_selector = str(kwargs.get("arg2", ""))
    link_field = str(kwargs.get("arg3", "complies"))

    target_ids = [
        str(n.get("id", ""))
        for n in needs
        if str(n.get("id", "")).startswith(id_prefix)
    ]

    linked_ids: set[str] = {
        ref
        for n in needs
        if _matches_source_selector(n, source_selector)
        for ref in n.get(link_field, [])
        if ref
    }

    connected = sum(1 for item_id in target_ids if item_id in linked_ids)
    not_connected = len(target_ids) - connected

    results.append(connected)
    results.append(not_connected)


def generic_pie_items_by_tag(
    needs: list[NeedItem], results: list[int], **kwargs: Any
) -> None:
    """Count tagged items split by whether selected source needs link them.

    Arguments are passed via ``arg1`` (tag), ``arg2`` (source selector prefix,
    matched against source ``type`` and ``id``), and ``arg3`` (link field
    name, default ``complies``).
    """
    results.clear()
    tag = str(kwargs.get("arg1", ""))
    source_selector = str(kwargs.get("arg2", ""))
    link_field = str(kwargs.get("arg3", "complies"))

    linked_ids: set[str] = {
        ref
        for n in needs
        if _matches_source_selector(n, source_selector)
        for ref in n.get(link_field, [])
        if ref
    }

    linked = 0
    not_linked = 0
    for n in needs:
        if tag in n.get("tags", []):
            if str(n.get("id", "")) in linked_ids:
                linked += 1
            else:
                not_linked += 1

    results.append(linked)
    results.append(not_linked)


def generic_pie_items_in_relationships(
    needs: list[NeedItem], results: list[int], **kwargs: Any
) -> None:
    """Count items of a given type by how many container items reference them.

    For every need of type *arg3*, counts how many needs of type *arg1*
    include its id in their *arg2* field.  Splits the result into three
    buckets: not referenced, referenced exactly once, referenced more than
    once.

    :filter-func: arguments:

        - ``arg1`` – type of the container needs (e.g. ``workflow``)
        - ``arg2`` – field on the container that holds references
          (e.g. ``output``)
        - ``arg3`` – type of the items to count (e.g. ``workproduct``)

    Appends to *results*:
    ``[not_referenced_count, referenced_once_count, referenced_multiple_count]``
    """
    results.clear()
    container_type = str(kwargs.get("arg1", ""))
    field = str(kwargs.get("arg2", ""))
    item_type = str(kwargs.get("arg3", ""))

    containers = [n for n in needs if n.get("type") == container_type]
    items = [n for n in needs if n.get("type") == item_type]

    item_counts: dict[str, int] = {str(n.get("id", "")): 0 for n in items}

    for container in containers:
        for ref in container.get(field, []):
            if ref in item_counts:
                item_counts[ref] += 1

    item_count_values = list(item_counts.values())
    not_referenced = item_count_values.count(0)
    referenced_once = item_count_values.count(1)
    referenced_multiple = len(item_count_values) - not_referenced - referenced_once

    results.append(not_referenced)
    results.append(referenced_once)
    results.append(referenced_multiple)


def _get_key_values(results: list[int], argument_paths: list[str]):
    """Append integer metric values selected by colon-separated paths.

    Each path is resolved against ``CALCULATED_METRICS`` (for example:
    ``"overall_metrics:total"``), converted to ``int``, and appended to
    ``results``.
    """
    metrics_json = CALCULATED_METRICS
    for raw_path in argument_paths:
        path = raw_path.strip()
        if not path:
            continue

        current: Any = metrics_json
        for key in path.split(":"):
            current = current[key]

        results.append(int(current))


def get_metrics_with_first_value_total(
    needs: list[Any], results: list[int], **kwargs: Any
) -> None:
    """
    This function calculates the first parameter you give it as the 'total'.
    E.g.
        - <func_call>(metrics_by_type:tool_req:total, metrics_by_type:tool_req:with_test_link)
    It will then treat the first arguemnt so 'tool_req-total' as the 'total number', and will
    subtract all following numbers from it.
    So in this case it would subtract the 'tool_req-with test link' number from the first.
    That way you can have a 'missing' value as the first.
    """
    results.clear()
    # As kwargs ordering is deterministic this will always put the first total into results[0]
    _get_key_values(results, [str(value) for value in kwargs.values()])

    results[0] -= sum(results[1:])


def get_just_metrics(needs: list[Any], results: list[int], **kwargs: Any) -> None:
    """Append selected metric values without any total/remainder calculation.

    All kwarg values are interpreted as colon-separated metric paths and
    appended to ``results`` in insertion order.
    """
    results.clear()
    _get_key_values(results, [str(value) for value in kwargs.values()])


def get_non_overlapping_link_metrics(
    needs: list[Any], results: list[int], **kwargs: Any
) -> None:
    """Compute mutually exclusive (non-overlapping) requirements-tests linkage categories.

    Use input from global state and overrides results input.

    1. **Remaining** — no testlink, no source_code_link
    2. **Test link only** — has testlink, no source_code_link
    3. **Code link only** — has source_code_link, no testlink
    4. **Fully linked** — has both testlink and source_code_link

    Suitable for ``needpie`` directives where overlapping
    categories produce misleading visualisations.
    """
    results.clear()
    total = int(CALCULATED_METRICS["overall_metrics"]["total"])
    with_test = int(CALCULATED_METRICS["overall_metrics"]["with_test_link"])
    with_code = int(CALCULATED_METRICS["overall_metrics"]["with_code_link"])
    fully = int(CALCULATED_METRICS["overall_metrics"]["fully_linked"])

    remaining = total - with_test - with_code + fully  # inclusion-exclusion
    only_test = with_test - fully
    only_code = with_code - fully

    results.extend([remaining, only_test, only_code, fully])
